# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OZaIigRTw0bnozmmMe1dP6UQYCzPqoTM
"""

import pandas as pd
import numpy as np
df=pd.read_csv('/content/ds_salaries.csv')
df['salary'].mean()

new=df['salary'].sort_values()
new

sampleArray =np.array([[34,43,73],[82,22,12],[53,94,66]])

sampleArray2=np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray3=np.vstack((sampleArray,sampleArray2))
sampleArray=pd.DataFrame(sampleArray3)
sampleArray

array1=np.array([10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33])
array2=np.hsplit(array1,3)
array2

sampleArray =np.array([[34,43,73],[82,22,12],[53,94,66]])
for i in range(3):
  a=sampleArray[0][i]
  sampleArray[0][i]=sampleArray[1][i]
  sampleArray[1][i]=a
sampleArray



sampleArray= np.array([[34,43,73],[82,22,12],[53,94,66]])
a=sampleArray[0].max()
b=sampleArray[1].min()
print(a)
print(b)

sampleArray=np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray=pd.DataFrame(sampleArray)
newColumn= np.array([[10,10,10]])
sampleArray[1]=[10,10,10]
sampleArray